title: Xu.Jian
email: xx2610@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  jekyll

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge



theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock



###########################################   顶部链接 设置
githubHomeURL:  https://github.com/Xu-Jian
# 这个是顶部 github Home 图标的链接. 
githubReadmeURL:  https://github.com/Xu-Jian/Xu-Jian.github.io

codePen_url:  http://codepen.io/Xu-Jian/
# 这个是顶部 codepen 图标的链接.

